- name: Install Docker
  hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Update apt package index
    apt:
      update_cache: yes
  - name: Install Docker
    apt:
      name: docker.io
      state: present
